language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coverage nose flake8 mock
  - pip install git+https://github.com/PyCQA/flake8-import-order.git
script:
  - PYTHONASYNCIODEBUG=1 python setup.py nosetests -s --with-coverage --cover-inclusive
notifications:
  email: false
