name: osrf_pycommon-ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
    build:
      strategy:
        matrix:
          os: [macos-latest, ubuntu-22.04, windows-latest]
          python: ['3.8', '3.9', '3.10', '3.11', '3.12']
          include:
          - os: ubuntu-20.04
            python: '3.6'
      name: osrf_pycommon tests
      runs-on: ${{matrix.os}}

      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install -U -e .[test] pytest-cov
      - name: Run tests
        run: |
          python -m pytest tests --cov=osrf_pycommon
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
